---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: ns1
  labels:
    app: nginx
    focus: cks
    tier: frontend
spec:
  containers:
  - name: nginx1
    image: nginx:latest
    ports:
    - name: http
      protocol: TCP
      containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: mongo1
  namespace: ns2
  labels:
    app: mongodb
    focus: cks
    tier: backend
spec:
  containers:
  - name: mongo1
    image: mongo:latest
    ports:
    - name: db
      protocol: TCP
      containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: mongo2
  namespace: ns3
  labels:
    app: mongodb
    focus: cks
    tier: backend
spec:
  containers:
  - name: mongo2
    image: mongo:latest
    ports:
    - name: db 
      protocol: TCP
      containerPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: mongo3
  namespace: ns4
  labels:
    tier: storage
    focus: cks
    app: mongodb
spec:
  containers:
  - name: mongo3
    image: mongo
    ports:
    - name: db
      protocol: TCP
      containerPort: 8081

