---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    focus: cks
    tier: frontend
  name: nginx1
  namespace: ns1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    focus: cks
    tier: frontend


---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    focus: cks
    tier: backend
  name: mongo1
  namespace: ns2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    focus: cks
    tier: backend
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    focus: cks
    tier: backend
  name: mongo1
  namespace: ns2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    focus: cks
    tier: backend

 
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    focus: cks
    tier: backend
  name: mongo2
  namespace: ns3
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    focus: cks
    tier: backend

---
apiVersion: v1
kind: Service
metadata:
  labels:
    focus: cks
    tier: storage
  name: mongo3
  namespace: ns4
spec:
  selector:
    tier: storage
    app: mongodb
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
