---
- name: Fetch public key from  
  hosts: control
  collections:
  - ansible.builtin
  - ansible.posix
  - ansible.netcommon
  - community.general
  tasks:
  - name: Setup fetch destination
    file:
      state: directory
      path: keys


- name: Setup public key access between all hosts
  hosts: servers
  remote_user: root
  collections:
  - ansible.builtin
  - ansible.posix
  - ansible.netcommon
  - community.general
  tasks:
  - name: Create SSH key for root user
    user:
      name: root
      generate_ssh_key: yes
      ssh_key_file: ~/.ssh/id_rsa
      ssh_key_bits: 4096
      ssh_key_comment: "root@{{ inventory_hostname }}"

  - name: Fetch keys
    fetch:
      src: ~/.ssh/id_rsa.pub
      dest: "keys/{{ inventory_hostname }}/id_rsa.pub"
      flat: true

  - name: List keys in control
    delegate_to: control
    shell: "ls {{ playbook_dir }}/keys"
    register: keys

  - name: Make tmp directory
    file:
      state: directory
      path: /tmp/keys.d

  - name: Copy every public key to every server
    loop: "{{ keys.stdout_lines }}"
    copy:
      src: "keys/{{ item }}/id_rsa.pub"
      dest: "/tmp/keys.d/{{ item }}.pub"

  - name: Create authorized_keys file
    shell: "cat /tmp/keys.d/*.pub > ~/.ssh/authorized_keys"

  - name: Remove tmp directory
    file:
      state: absent
      path: /tmp/keys.d
