---
- name: Group nodes 
  import_playbook: playbooks/control.yml
  vars:
    site_directory: /home/ansible/k8s 

- name: Bootstrap primary node 
  import_playbook: playbooks/primary.yml
  vars:
    site_directory: /home/ansible/k8s 

- name: Setup HA
  when: ha is defined 
  import_playbook: playbooks/ha.yml
  vars:
    site_directory: /home/ansible/k8s 

- name: Setup workers
  import_playbook: playbooks/worker.yml
  vars:
    site_directory: /home/ansible/k8s 

