---
- name: Group nodes 
  import_playbook: playbooks/setup_localhost.yml
  vars:
    site_directory: /home/ansible/kubernetes

- name: Bootstrap primary node 
  import_playbook: playbooks/init.yml
  vars:
    site_directory: /home/ansible/kubernetes

- name: Setup container networking plugin
  import_playbook: playbooks/deploy_cni_plugin.yml
  vars:
    cni_plugin: ""

- name: Join additional nodes to the control-plane 
  when: |
    ( enable_join_control_plane is defined ) and
    ( enable_join_control_plane == 'true' )
  import_playbook: playbooks/join_control_plane.yml
  vars:
    site_directory: /home/ansible/kubernetes

- name: Join workers to the cluster
  import_playbook: playbooks/join.yml
  vars:
    site_directory: /home/ansible/kubernetes

- name: Approve certificate requests for kubelet
  import_playbook: playbooks/approve_csrs.yml
  vars:
    site_directory: /home/ansible/kubernetes

