---
- name: Remove containers and disable kubelet
  hosts: allnodes
  tasks:
  - name: Disable kubelet
    service:
      name: kubelet
      enabled: no
      state: stopped

  - name: Force remove all containers
    command: crictl rm -fa 2>/dev/null

  - name: Remove existing kubernetes configuration
    file:
      path: /etc/kubernetes
      state: absent

  - name: Remove existing etcd configuration
    file:
      path: /var/lib/etcd
      state: absent
