---
- name: Teardown cluster
  hosts: allnodes
  tasks:
  - name: Reset all nodes using kubeadm
    command: kubeadm reset --force
    ignore_errors: yes
  
  - name: Delete local facts setup from previous runs if any
    file:
      path: /etc/ansible/facts.d
      state: absent
