apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredLabels
metadata:
  name: requirelabels 
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace","Pod"]
  parameters:
    labels: ["yield"]
