---
- name: Turn off swap
  command: swapoff -a

- name: Check for swap mounts
  register: swap_mounts
  ignore_errors: yes
  shell: grep -ie "swap" /etc/fstab | grep -v "#"

- name: Disable swap mounts
  when: |
    ( swap_mounts.stdout_lines | count > 0 ) and
    ( swap_mounts.rc == 0)
  loop: "{{ swap_mounts.stdout_lines }}"
  lineinfile:
    regex: "^{{ item }}"
    line: "#{{ item }}"
    state: present
    path: /etc/fstab
