---
- name: Setup temp files directory
  file:
    state: directory
    path: "{{ kubeadm_config_files_dir }}"

- name: Copy config files for init-node
  loop: "{{ kubeadm_join_node_config_files }}"
  template:
    src: "{{ item }}.j2"
    dest: "{{ kubeadm_config_files_dir }}/{{ item }}.yml"

- name: Remove exising config file
  file:
    state: absent
    path: "{{ kubeadm_config_file }}"

- name: Touch config file
  file:
    state: touch
    path: "{{ kubeadm_config_file }}"

- name: Create kubeadm config file
  loop: "{{ kubeadm_join_node_config_files }}"
  shell: "cat {{ kubeadm_config_files_dir }}/{{ item }}.yml >> {{ kubeadm_config_file }}"

- name: Remove temp files directory
  file:
    state: absent
    path: "{{ kubeadm_config_files_dir }}"

- name: Reset before init
  shell: kubeadm reset --force

- name: Join cluster 
  shell: kubeadm join --config "{{ kubeadm_config_file }}"

- name: Symlink kubeconfig
  include_tasks: subtasks/symlink_kubeconfig.yml
  vars:
    config_file_name: admin.conf

