---
- name: Configure Swap
  when: swap == false
  include_tasks: configure_swap.yml

- name: Configure Kernel
  include_tasks: configure_kernel.yml

- name: Configure Falco
  when: |
    (enable_falco is defined) and
    (enable_falco == 'true')
  include_tasks: configure_falco.yml

- name: Configure SELinux
  when: "ansible_facts['os_family'] == 'RedHat'"
  include_tasks: configure_selinux.yml

- name: Configure Services
  include_tasks: configure_services.yml

- name: Install packages
  include_tasks: configure_packages.yml

- name: Reboot node
  reboot:
   test_command: uptime

- name: Start the cluster 
  when: '"control_plane" in group_names'
  include_tasks: start_cluster.yml

- name: Join node to the cluster 
  when: '"worker_nodes" in group_names'
  include_tasks: join_cluster.yml 
