---
- name: Configure Swap
  when: swap == false
  include_tasks: configure_swap.yml

- name: Configure Kernel
  include_tasks: configure_kernel.yml

- name: Configure Falco
  when: "enable_falco == 'true'"
  include_tasks: configure_falco.yml

- name: Configure SELinux
  when: "ansible_facts['os_family'] == 'RedHat'"
  include_tasks: configure_selinux.yml

- name: Configure Services
  include_tasks: configure_services.yml

- name: Install packages
  include_tasks: install_packages.yml

- name: Reboot node
  reboot:
   test_command: uptime

- name: Configure control plane nodes
  when: '"control_plane" in group_names'
  include_tasks: control_plane.yml

- name: Configure worker plane nodes
  when: '"worker_plane" in group_names'
  include_tasks: worker_plane.yml
