- name: Create config.yml file for additional-node
  loop:
  - JoinConfiguration.j2
  - KubeletConfiguration.j2
  blockinfile:
    path:  /etc/kubernetes/config.yml
    marker_begin: "---"
    marker_end: "\n"
    block: "{{ lookup('file','{{ item }}') }}"

- name: Join cluster 
  shell: kubeadm join --config /etc/kubernetes/config.yml

- name: Setup kubeconfig
  include_tasks: copy_kubeconfig.yml
  vars:
    config_file_name: admin.conf

