- name: Copy configuration file for kubeadm
  template:
    src: join_config.j2
    dest: /etc/kubernetes/config.yml

- name: Join cluster 
  shell: kubeadm join --config /etc/kubernetes/config.yml

- name: Setup kubeconfig
  include_tasks: copy_kubeconfig.yml
  vars:
    config_file_name: admin.conf

