---
- name: Reset before init
  shell: kubeadm reset --force

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes

- name: Run kubeadm init
  when: primary == true
  include_tasks: subtasks/init_control_plane.yml

- name: Run kubeadmin join --control-plane
  when: primary == false
  include_tasks: subtasks/join_control_plane.yml
