---
# defaults file for roles/master_node
loadable_modules:
- br_netfilter

kernel_parameters:
- key: net.ipv4.ip_forward
  value: 1
- key: net.bridge.bridge-nf-call-ip6tables
  value: 1 
- key: net.bridge.bridge-nf-call-iptables
  value: 1

swap: no 

basearch: x86_64
kubernetes_repo:
  name: Kubernetes 
  description: Kubernetes
  baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ basearch }}
  enabled: yes
  gpgcheck: yes
  gpgkey: 
  - https://packages.cloud.google.com/yum/doc/yum-key.gpg
  - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  excludes:
  - kubelet
  - kubeadm
  - kubectl

k8s_cluster_name: workstation 
k8s_cluster_version: v1.23.1
k8s_version: 1.23.1-0
k8s_packages:
- kubeadm-{{ k8s_version }}
- kubectl-{{ k8s_version }}
- kubelet-{{ k8s_version }}
- iproute-tc
- jq
- python3
- python3-pip

pip_packages:
- openshift

api_loadbalancer: lbinternal.example.com
api_server_endpoint: "{{ api_loadbalancer }}:6443"
pod_network_cidr: 192.168.0.0/16
service_network_cidr: 10.96.0.0/12

bootstrap_token_description: "The default bootstrap token generated by 'kubeadm init'."
auth_extra_groups: "system:bootstrappers:kubeadm:default-node-token"


falco:
  falco_gpg_key: https://falco.org/repo/falcosecurity-3672BA8F.asc
  falco_repo_url: https://download.falco.org/packages/rpm
