---
# Swap 
swap: no 

# SELinux parameters (primarily for RedHat family of distros)
selinux: 
  state: permissive
  policy: targeted

# Kernel parameters
kernel_modules:
- br_netfilter
kernel_parameters:
- key: net.ipv4.ip_forward
  value: 1
- key: net.bridge.bridge-nf-call-ip6tables
  value: 1 
- key: net.bridge.bridge-nf-call-iptables
  value: 1


# Kubernetes setup parameters
kubernetes_repo:
  name: Kubernetes 
  description: Kubernetes
  baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ ansible_facts['architecture']}}
  enabled: yes
  gpgcheck: yes
  gpgkey: 
  - https://packages.cloud.google.com/yum/doc/yum-key.gpg
  - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  excludes:
  - kubelet
  - kubeadm
  - kubectl
kubernetes_version: 1.23.1-0
kubernetes_packages:
- kubeadm-{{ kubernetes_version }}
- kubectl-{{ kubernetes_version }}
- kubelet-{{ kubernetes_version }}
- iproute-tc
- jq
- python3
- python3-pip
python_modules:
- openshift

# Kubeadm parameters
kubeadm_temp_config_files_location: /tmp/kubeadmConfigFiles/
kubeadm_config_file: /etc/kubernetes/config.yml
kubeadm_init_node_config_files:
  - InitConfiguration
  - KubeletConfiguration
  - ClusterConfiguration
kubeadm_join_node_config_files:
- JoinConfiguration
- KubeletConfiguration

# Cluster parameters
kubernetes_cluster_name: workstation 
kubernetes_cluster_version: v1.23.1


api_loadbalancer: lbinternal.example.com
api_server_endpoint: "{{ api_loadbalancer }}:6443"
pod_network_cidr: 192.168.0.0/16
service_network_cidr: 10.96.0.0/12

bootstrap_token_description: "The default bootstrap token generated by 'kubeadm init'."
auth_extra_groups: "system:bootstrappers:kubeadm:default-node-token"


falco:
  falco_gpg_key: https://falco.org/repo/falcosecurity-3672BA8F.asc
  falco_repo_url: https://download.falco.org/packages/rpm
