---
- name: Clear repository folder 
  file:
    state: absent
    path: "{{ custom_repo_folder }}"

- name: Setup repository folder
  file:
    state: directory
    path: "{{ custom_repo_folder }}"

- name: Download packages
  loop: "{{ extra_packages }}"
  shell: "dnf install --assumeyes --downloadonly --downloaddir {{ custom_repo_folder }} \"{{ item }}\""
#  dnf:
#    name: "{{ item }}"
#    download_dir: "{{ custom_repo_folder }}"
#    download_only: yes

- name: Install createrepo_c
  dnf:
    name: createrepo_c
    state: present

- name: Create repository from folder
  shell: createrepo {{ custom_repo_folder }}
