---
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  namespace: sp1
  labels:
spec:
  containers:
  - name: nginx
    image: nginx:1.21.6
    ports:
    - name: http
      containerPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  namespace: sp2
  labels:
    yield: cks
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: mongo1 
  namespace: sp3
  labels:
    yield: cks
    app: mongodb
    tier: backend
spec:
  containers:
  - name: mongodb
    image: mongo:5.0.6
    ports:
    - name: db
      containerPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: mongo2
  namespace: sp4
  labels:
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    ports:
    - name: db
      containerPort: 8080
      protocol: TCP

