---
apiVersion: v1
kind: Service
metadata:
  name: nginx1
  namespace: sp1
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: sp2
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mongo1 
  namespace: sp3
spec:
  selector:
    app: mongodb
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mongo2
  namespace: sp4
spec:
  selector:
    app: mongodb
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
