---
- name: Setup managed hosts
  hosts: servers
  collections:
  - ansible.builtin
  - ansible.posix
  - ansible.netcommon
  - community.general
  gather_facts: false
  tasks:
  - name: Configure hosts file 
    template:
      src: ../templates/hosts.j2
      dest: /etc/hosts

  - name: Configure AppStream remote repository
    yum_repository:
      name: dvd_appstream
      description: AppStream
      file: dvd_appstream
      baseurl: ftp://control.sysctls.com/pub/dvd/AppStream/
      gpgcheck: yes
      gpgkey: 
      - ftp://control.sysctls.com/pub/dvd/RPM-GPG-KEY-redhat-beta
      - ftp://control.sysctls.com/pub/dvd/RPM-GPG-KEY-redhat-release

  - name: Configure BaseOS remote repository
    yum_repository:
      name: dvd_baseos
      description: BaseOS
      file: dvd_baseos
      baseurl: ftp://control.sysctls.com/pub/dvd/BaseOS/
      gpgcheck: yes
      gpgkey: 
      - ftp://control.sysctls.com/pub/dvd/RPM-GPG-KEY-redhat-beta
      - ftp://control.sysctls.com/pub/dvd/RPM-GPG-KEY-redhat-release

  - name: Update all packages
    dnf:
      name: "*"
      state: latest
